spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/main-db
  sql:
    init:
      mode: always
logging:
  level:
    ru.practicum.mainService: debug
stats-server:
  url: http://localhost:9090

server:
  port: 8080